### ISSUE TITLE
Get_user_function_2_state - set to supported None while most likely should be all

### ISSUE THREAD

**Issue by convicte** [veista/nilan#152]
This feature is the second relay switch available on many (if not all) Nilan units, to allow triggering from external devices, such as kitchen hoods and similar
``` yaml
    "get_user_function_2_state": {
        "entity_type": "binary_sensor",
        "min_bus_version": 2,
        "min_hps_bus_version": 1,
        "supported_devices": (None,),
```
It's currently listed as supported by `NONE` but I would recommend switching to `all`, which in a worse case scenario would be disabled as sensor by user.
